language: android

addons:
    apt:
        packages:
        - libgd2-xpm
        - ia32-libs
        - ia32-libs-multiarch
        - git
        - libtool
        - automake
        - gradle

android:
    components:
    - platform-tools
    - android-21
    - build-tools-21.1.2
    - extra

jdk: oraclejdk7

notifications:
  email: false

before_install:
    - openssl aes-256-cbc -K $encrypted_0a2f236f25bc_key -iv $encrypted_0a2f236f25bc_iv -in release.jks.enc -out release.jks -d
    - bash .travis/setup.sh
    - source .travis/env.sh

cache:
    directories:
    - $HOME/ndk/

script:
    - bash .travis/build.sh

deploy:
  provider: releases
  api-key: $GITHUB_TOKEN
  file:
    - "$HOME/ShadowVPN-debug-v$VERSION.apk"
    - "$HOME/ShadowVPN-release-v$VERSION.apk"
  skip_cleanup: true
  on:
    tags: true
env:
    global:
        - secure: "SMuUyFPMHB9zeR+uf7ferr168tO17/xxt2UQ9BBIuR3QoiVWFZ0tasLXhQMW2Jv2MBqi8AM6IiU3EN302trwyktJBoMpJtt77D8D+lBtQlvE7WuBHKnFvqvhpmRy1uhbzqeJcSUg27NEJT2Z++KINYanlHdRbRajIURJmbJisn1gHL96YuYcgf1RevRuRv+Rpk6z+Rfwl7ZYeYy/18HRqar8ZNTEvikqUhLIIKM4fCPZa1wN5C7Fst7acC0ElYcMMpom6LXY5Db4zpRESMnHKNPYzb3mqh3UeHlKohpaiLgz5KyAMSxOATcQ1TSGmiVpD4J6TMh1mqrgdFMwt75iYN26NRXqPiyFD1l9X85aWI6Z0hk3k13STVoY6ESY+KGokGUxqAvJojA20Whpcugqtha/RkRB6Mshf+aHCIudLjVNt91OBtU5vRX6LrA02VRGnNu9ME6+GUQKhntvfUg3ZT3Zg8onFMKRTZEnuC40aFbHWQBo4Lpozyp+uPK4sb0pt+V3lXRUy/8J1o/MD1HrIkzAuineqiBuoRRIxvhFwXcmMJ26GcEq6kK22O7dy0SeWU31bpU5TQ1dlfML9KQldcpXB2BROlx8n6GIOK6tl1sThrz1sAR0J++lStgttcKbmHciMHAz+AeWDsWaurdD8L3zzFOfutGHZSepeZzDYj8="
        - secure: "bGdpKal2/4Slytux75ANoxCOxATfTO8EVR3R/ebT2bRZ0DmijsXyhYu9NTM+3STw/zWOMBKdE/2DSG4acU0Imh5JM+3/FRvuoEPWBfbEooc5629RjpHbGUt2j0xb5cSaAwM6U8ynWOhVX0F1NWCK8VVBs7YWhIWL4WCpciyygJ/GzQ+ywEV1POToTWv5DkFiIfevLdVsSJJSZCi/f3xejgPGI9lL/IbQ7BtqVEg19Le/YItV4ProHiXAluH1U/8qLfM61LWV3XbSokZRr5KItMHQdaQGo/hLJV/p81lTTJvNuBm1sf2H9rRfOcDDLV9EAq0zHsK8YHv3egWfeokC0gPMGfcw72g7LnRh8/AFnZvznVsOhxmZM7VxKgsczkLZC80iwMqfRcsYrdkFRhT4pO8ci3DN9CQzlFG8jOxv7tevPxpbDmtwD/EaIhVVm17uj8/UBhxu/+DtBBX0v+mD46PeQdmttYhddr1NjZKDkw2rUbOurJR8mpZcOw/in39R4dmNv/u0on5jXsDdwBuA2E1D5iL6qsmwkWxCzBZgzhQ3/BTzG15b7iOp01QmW+D9yJ5cARIePIE8eRilFKlVtEm14iQNoYiMFJPN87z12Dsquwox4TIQbrg8538pSvO/M1UxGKQJGFJeDZkmLkl2zpmvL1l1BHo3DjPJ11OA1h4="
        - secure: "U8roN5xNbRXA4MyduYJjIHaaUYh/UOhjmZeM9nz/Bm11ABRdBoHX81pL60QfElBC3KiwwcScTj369Q/Vqwky9xspK7beops4fPtph5BYFDQJJcpxV6GwAtf7mdzG4DoKNnAgqmM5StxFUP52uOmzSzLVKW9/ruE46J1mVcfCEhCyAPCNhaDbqBCHKmlUHXXWWrzkBhxCaiWPjEy1PObziy+kRYXT0HSTQCy/knrJWyCoxu4MV+v+8SakHdHQ6Fx7z22Tb/M8J3Hc6EsNJ5KARCi2GWwkrODisw3O9k3bNmSlCBJyMlXGP2+r9PhjTQnbmr8JvBlW8GOLjQioRiPzQMWrHv1qXzzE+/FkwiQSd/vO4R+Gono7erSWSWQ3tbASwx1YPdCF1M+0PErXr7mRBy/2TRgDIqeWJoiBYYWBQU4dqse1tZbkaXE/vH19YjdcDCHoN+XX9Ke9kJg+AQCMN3VElVNBTMLzAbSkUGLXwslrvv9OeeKN4cbTooAes/1cnjTczTWPjwZoi2tNNDjEqevu/XYy5bj05wL290BiQcEUMoJDxEaYJJ1NBTExfbhiT68AdUv921jhQd4OUjRVJXJReLxst7j1dbTiYCSlexCCzdEaxFeejzvMQZCP5nt0N3QZ57/JiKXMJcJMgamZRsDkWfnioncihXZgF+tD8cM="
        - secure: "oqct2jKN2qQroD18oZ1aLA3bg6wtsE9LHoXBVJfYQ6TAeJwTDsYTWz2qQ5MmgAeCmphZiD+/r89QqO+/+Ew8T0H0aPgOYTT/TRbgs6OMF7/AIJDcGNF/qNsR3X5jaMoPRpo+Pes0nciZTNVRV6+I5Y0WLvx8KEOdRZ20FBne6jKLp2hehD7KK24H19pNT4tY4CIDQRFihTwTAvtYJkC/Qk4mTY8zjxi6Fd2KepakrpLh7OoX1spo3YY8T0KfkPuwP5H6tW1ioNYvAptHvvwmZsHqejOo1A8wC0FHtv/x2xTIXUniMB71PlYrEcM6MnwXM/1FNxX+2p5fTbac2KtF9dMsO8rcAl4iVesHR8DCFNFq/Z7UV8PN41YJsp0dKkeOPKbaRcq8W5s6+tV92pDcCMFo/u6fEnxC2g/HWixunb7qQnxM7WW/WzlOokTtCx8feiIycc1EKfPVLJQF1Y70oZqkZLCZietl3Y/uY2v0AzdUibZa3F5P12unYq65xB7FfxJgYeAOEAmQUpzURydLS1S1fF6NoATELONNfH6D+8TqNenbQZLh396ZBIe2rJbOqnyAuD8qMsRH5azo6ovxINoONIuxBZoaB5SwygOK9qa0dvMCYAajyOEMw6omFSbALen+TUN1ltY8IFU6Ph6DiDy8EmPiIYlBK3zcBHgCgk8="
